AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.examples.HelloWorld
      Runtime: java8
      CodeUri: ./target/HelloWorld-1.0.jar
